### ISSUE TITLE
Upgrade elastic search for np and p

### ISSUE THREAD

**Issue by ruabr** [dfds/ded-grafana-dashboards#27]
We have outgrown our elastic search configuration so it needs an upgrade to be sustainable on the long run.

- [x] Increase Diskspace on nonprod and prod to 500 GB

- [x] Figure out which intances to upgrade master or data nodes

- [x] Upgrade the relevant instances

**Comment by samidbb** [comment]
nonprod and prod upgraded as follows:
     machine type: m4.large -> m4.xlarge
     Diskspace: 80 GB -> 500 GB
Refer to history in https://github.com/dfds/aws-elasticsearch
