### ISSUE TITLE
Indicate environment in Grafana dashboards

### ISSUE THREAD

**Issue by raras-dfds** [dfds/ded-grafana-dashboards#3]
Dashboards are completely identical between environments. We need some way of differentiating. It could be different background colours, environment appended to title, or something else.

Environment could be appended to dashboard title, by transforming each dashboard through the download script.

Changing the background colour could be done by making and deploying custom Grafana themes.

- [x] add ec2_sd_configs section to prometheus to get ec2 information (using Node-Exporter)
- [x] ~~add AmazonEC2ReadOnly (or more restictive) permissions to cluster nodes~~
- [x] use label in Grafana dashboards
- [x] add to existing dashboards

**Comment by samidbb** [comment]
changes are put into the dfds/ded-grafana-dashboards repo
