### ISSUE TITLE
Get notified of low resources in ES

### ISSUE THREAD

**Issue by ruabr** [dfds/ded-grafana-dashboards#41]
- [x] memory pressure

- ~~CPU usage~~

**Comment by samidbb** [comment]
Alert rules added but not deployed.
Rules based on relevant metrics from docs:
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/es-metricscollected.html
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-handling-errors.html#aes-handling-errors-red-cluster-status
