### ISSUE TITLE
Get notified in slack of taints in k8s

### ISSUE THREAD

**Issue by ruabr** [dfds/ded-grafana-dashboards#42]

**Comment by samidbb** [comment]
What needs to be reviewed:
- Labels
- Slack message format (seems to put all alerts in single slack message)

**Comment by rifisdfds** [comment]
@samdi-dfds I have commented these rules out in source for now as the pipeline I have created uses a template and we need to go over the rules to add environment labels and maybe alter the queries where applicable to bring more data
